# Generated by Django 5.1.7 on 2025-04-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_product_qty_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
